controller_list:
  - name: /crustcrawler
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: /crustcrawler/end_effector/gripper
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_finger_joint
      - right_finger_joint
